#!/bin/bash

# find go function definition in a git repo
# requires:  ripgrep, git, grep
#
# shell usage:
#	- godeff <func name>
#
# acme usage:
#	- highlight a function name in go code
#	- click and hold button 2 on 'godeff'
#	- click button 1, then release both buttons
#

wd=$(git rev-parse --show-toplevel)
rg -Hn "$1\((.*,)* *(.*)\)" $wd | grep 'func ' | plumb -i -d edit -a "action=showdata filename=$wd:go/fndef/$1"