#!/bin/bash

# find go function references in a git repo
# requires:  ripgrep, git, grep
#
# shell usage:
#	- goreff <func name>
#
# acme usage:
#	- highlight a function name in go code
#	- click and hold button 2 on 'goreff'
#	- click button 1, then release both buttons
#

wd=$(git rev-parse --show-toplevel)
rg -Hn "$1\((.*,)* *(.*)\)" $wd | grep -v 'func ' | plumb -i -d edit -a "action=showdata filename=$wd:go/fnref/$1"